import com.mysema.query.jpa.impl.JPAQuery;

import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public String getGreeting() {
        return StringUtil.trim("Hello world.");
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        EntityManagerFactory entityManagerFactory = Persistence.createEntityManagerFactory("org.hibernate.tutorial.jpa");
        EntityManager entityManager = entityManagerFactory.createEntityManager();

        QCustomer customer = QCustomer.customer;
        JPAQuery query = new JPAQuery(entityManager);
        Customer bob = query.from(customer).where(customer.firstName.eq("Bob")).uniqueResult(customer);
    }
}
